### ISSUE TITLE
How to compute the Jacobian based on the residual?

### ISSUE THREAD

**Issue by Kenzo2511** [koide3/caratheodory2#2]
Hi everyone,
![image](https://github.com/koide3/caratheodory2/assets/120498998/3d174d09-c621-41a6-9e50-dc8bfcf0567d)
I want to compute the Jacobian matrix from residual. I don't understand the derivatives of a residual ek. 
Can anyone help me? Thanh you very much.
Duy Nhat

**Comment by koide3** [comment]
Please take a look at code like [this](https://github.com/SMRT-AIST/fast_gicp/blob/0f54bc7797f83c20ae88829440679709c30cc5b6/include/fast_gicp/gicp/impl/fast_gicp_impl.hpp#L188).

**Comment by ghost** [comment]
@koide3 Thank you very much
